// <auto-generated />
using System;
using ControleDeOrcamentoFamiliar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleDeOrcamentoFamiliar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220120000858_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("ControleDeOrcamentoFamiliar.Receitas", b =>
                {
                    b.Property<int>("IdReceita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataReceita")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoReceita")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ValorReceita")
                        .HasColumnType("double");

                    b.HasKey("IdReceita");

                    b.ToTable("receitas");
                });
#pragma warning restore 612, 618
        }
    }
}
